import './globals.css'
import { Inter, Heebo } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const heebo = Heebo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${heebo.className} bg-ghost-white`}>{children}</body>
    </html>
  )
}
